# Generated by Django 5.1.4 on 2024-12-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_dynamicfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicField',
        ),
    ]
